import Models.*
import com.jamesward.zio_mavencentral.MavenCentral

import java.io.{ByteArrayOutputStream, File}
import java.nio.file.Files
import java.util.jar.{JarEntry, JarOutputStream, Manifest}
import scala.jdk.CollectionConverters.*

object JarCreator:

  // todo: use zio-streams-compress-zip
  def create(
    skillDir: File,
    org: Org,
    repo: Repo,
    skillName: SkillName,
    pom: String,
    groupId: MavenCentral.GroupId,
    artifactId: MavenCentral.ArtifactId,
    version: MavenCentral.Version,
  ): Array[Byte] =
    val baos = ByteArrayOutputStream()
    val manifest = Manifest()
    manifest.getMainAttributes.putValue("Manifest-Version", "1.0")
    manifest.getMainAttributes.putValue("Created-By", "skillsjars.com")

    val jar = JarOutputStream(baos, manifest)

    // todo: we need subdirs in this path
    val resourcePrefix = s"META-INF/resources/skills/$org/$repo/$skillName/"

    addSkillFiles(jar, skillDir, resourcePrefix)

    val mavenPrefix = s"META-INF/maven/$groupId/$artifactId/"

    addEntry(jar, s"${mavenPrefix}pom.xml", pom.getBytes("UTF-8"))

    val properties =
      s"""#Generated by SkillsJars
         |version=$version
         |groupId=$groupId
         |artifactId=$artifactId
         |""".stripMargin
    addEntry(jar, s"${mavenPrefix}pom.properties", properties.getBytes("UTF-8"))

    jar.close()
    baos.toByteArray

  private def addEntry(jar: JarOutputStream, path: String, content: Array[Byte]): Unit =
    jar.putNextEntry(JarEntry(path))
    jar.write(content)
    jar.closeEntry()

  private def addSkillFiles(jar: JarOutputStream, dir: File, prefix: String): Unit =
    val createdDirs = scala.collection.mutable.Set.empty[String]

    def ensureDir(path: String): Unit =
      if !createdDirs.contains(path) then
        val parts = path.split('/').filter(_.nonEmpty)
        var current = ""
        for part <- parts do
          current = if current.isEmpty then s"$part/" else s"$current$part/"
          if !createdDirs.contains(current) then
            jar.putNextEntry(JarEntry(current))
            jar.closeEntry()
            createdDirs += current

    def addFilesFrom(directory: File, currentPrefix: String): Unit =
      val files = Option(directory.listFiles()).getOrElse(Array.empty[File])
      for file <- files.sortBy(_.getName) do
        if file.isDirectory then
          addFilesFrom(file, s"$currentPrefix${file.getName}/")
        else
          ensureDir(currentPrefix)
          val content = Files.readAllBytes(file.toPath)
          addEntry(jar, s"$currentPrefix${file.getName}", content)

    addFilesFrom(dir, prefix)
