import Models.*
import com.jamesward.zio_mavencentral.MavenCentral
import zio.*
import zio.compress.*
import zio.stream.*

import java.io.File
import java.nio.file.Files
import scala.jdk.CollectionConverters.*

object JarCreator:

  def create(
    skillDir: File,
    org: Org,
    repo: Repo,
    skillName: SkillName,
    pom: String,
    groupId: MavenCentral.GroupId,
    artifactId: MavenCentral.ArtifactId,
    version: MavenCentral.Version,
    subPath: List[String] = List.empty,
  ): ZIO[Any, Throwable, Array[Byte]] =
    val subPathPart = if subPath.isEmpty then "" else subPath.mkString("", "/", "/")
    val resourcePrefix = s"META-INF/resources/skills/$org/$repo/$subPathPart$skillName/"
    val mavenPrefix = s"META-INF/maven/$groupId/$artifactId/"

    val manifestContent = "Manifest-Version: 1.0\r\nCreated-By: skillsjars.com\r\n\r\n".getBytes("UTF-8")

    val properties =
      s"""#Generated by SkillsJars
         |version=$version
         |groupId=$groupId
         |artifactId=$artifactId
         |""".stripMargin

    def fileEntry(name: String, content: Array[Byte]): (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte]) =
      (ArchiveEntry(name = name), ZStream.fromChunk(Chunk.fromArray(content)))

    def dirEntry(name: String): (ArchiveEntry[Option, Any], ZStream[Any, Throwable, Byte]) =
      (ArchiveEntry(name = name, isDirectory = true), ZStream.empty)

    val skillFileEntries = ZIO.attemptBlocking:
      val basePath = skillDir.toPath
      val stream = Files.walk(basePath)
      try
        val allPaths = stream.iterator().asScala.toList.sorted
        allPaths.flatMap: path =>
          if path.equals(basePath) then None
          else
            val relative = basePath.relativize(path).toString.replace('\\', '/')
            if Files.isDirectory(path) then
              Some(dirEntry(s"$resourcePrefix$relative/"))
            else
              Some(fileEntry(s"$resourcePrefix$relative", Files.readAllBytes(path)))
      finally
        stream.close()

    skillFileEntries.flatMap: skillEntries =>
      val allEntries = ZStream.fromIterable(
        Seq(fileEntry("META-INF/MANIFEST.MF", manifestContent)) ++
        skillEntries ++
        Seq(
          fileEntry(s"${mavenPrefix}pom.xml", pom.getBytes("UTF-8")),
          fileEntry(s"${mavenPrefix}pom.properties", properties.getBytes("UTF-8")),
        )
      )
      allEntries.via(ZipArchiver.archive).runCollect.map(_.toArray)
