sources = [
  {
    group-id = "com.skillsjars"
    exclude-artifacts = ["*maven-plugin", "*gradle-plugin"]
    security-scanned = true
  },
  {
    group-id = "com.jamesward"
    artifact-id = "skills"
    security-scanned = false
  },
  {
    group-id = "org.springaicommunity"
    artifact-id = "spring-testing-skills"
    security-scanned = false
  }
]
